### ISSUE TITLE
rgrgr

### ISSUE THREAD

**Issue by fedoroff94** [nikita-volkov/graph-db#9]
здарова, отец)

**Comment by nikita-volkov** [comment]
Что происходит? :)

**Comment by fedoroff94** [comment]
Привет) извини за беспокойство, делал тестовое задание с апишкой гита, возможно добавил тебе issue в какой-нибудь репозиторий) я не специально)) 15.12.2021, 17:44, "Nikita Volkov" ***@***.***>: Что происходит? :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.     -- Best regards,Fedenkov ArtemSoftware EngineerFresh Lime ***@***.***  Follow FreshLime people!
